export const CAMBIAR_VALOR_BUSQUEDA = "CAMBIAR_VALOR_BUSQUEDA";
export const REQUEST_API_PENDIENTE = "REQUEST_API_PENDIENTE";
export const REQUEST_API_COMPLETADA = "REQUEST_API_COMPLETADA";
export const REQUEST_API_ERROR = "REQUEST_API_ERROR";
